data:
  dataset: fivek
  camera: NIKON_D700
  data_dir: ./data/fivek_dataset_processed/fivek
  file_list_val: NIKON_D700_test.txt
  rgb_size: "2X"
  num_workers: 4

checkpoint: ./ckpt/nikon_d700.pth
camera: NIKON_D700
use_fusion: false
context_size: 256
patch_size: 512
overlap: 16
device: cuda:0
batch_size: 1
seed: 42
limit: 0

output_dir: ./test_output/rawflow_NIKON_D700
save_visualizations: true
save_raw_outputs: false
visualization_quality: 95
